services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build:
      context: ./services/api-gateway
    environment:
      - REDIS_URL=redis://redis:6379/0
      - TAAS_QUEUE_NAME=taas
      - API_KEY=${API_KEY:-dev-key}
      - TAAS_RESULTS_DIR=/workspace/test-results/taas
      - TAAS_UPLOAD_DIR=/workspace/test-results/taas/uploads
      # Postgres
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=taas
      - PGPASSWORD=taas
      - PGDATABASE=taas
    volumes:
      - ./:/workspace
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - perf
      - zap
      - postgres

  worker:
    build:
      context: ./workers/worker
    environment:
      - TAAS_RESULTS_DIR=/workspace/test-results/taas
      - RQ_REDIS_URL=redis://redis:6379/0
      # Postgres
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=taas
      - PGPASSWORD=taas
      - PGDATABASE=taas
      # MinIO/S3
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_BUCKET=taas-artifacts
      - S3_REGION=us-east-1
      - ARTIFACT_TTL_SECONDS=86400
      # Thresholds (optional)
      # - PERF_SCORE_MIN=80
      # - PERF_LCP_MAX_MS=2500
      # - PERF_CLS_MAX=0.1
      # - PERF_TTI_MAX_MS=5000
      # - ZAP_ALLOW_MEDIUM=0
      # - ZAP_ALLOW_HIGH=0
    volumes:
      - ./:/workspace
    shm_size: "1gb"
    depends_on:
      - redis
      - perf
      - zap
      - postgres
      - minio

  dashboard:
    build:
      context: ./services/dashboard
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_API_KEY=dev-key
      - NEXT_PUBLIC_S3_PUBLIC=http://localhost:9000
    ports:
      - "3000:3000"
    depends_on:
      - api

  perf:
    build:
      context: ./services/perf-lighthouse
    environment:
      - PORT=3001
      - CHROME_PATH=/usr/bin/chromium
    ports:
      - "3001:3001"

  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    command: ["zap.sh", "-daemon", "-host", "0.0.0.0", "-port", "8090", "-config", "api.addrs.addr.name=.*", "-config", "api.addrs.addr.regex=true", "-config", "api.key=${ZAP_API_KEY:-changeme}"]
    environment:
      - ZAP_API_KEY=${ZAP_API_KEY:-changeme}
    ports:
      - "8090:8090"

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=taas
      - POSTGRES_USER=taas
      - POSTGRES_PASSWORD=taas
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data

volumes:
  pgdata: {}
  minio: {}
