services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build:
      context: ./services/api-gateway
    environment:
      - REDIS_URL=redis://redis:6379/0
      - TAAS_QUEUE_NAME=taas
      - API_KEY=${API_KEY:-dev-key}
      - TAAS_RESULTS_DIR=/workspace/test-results/taas
    volumes:
      - ./:/workspace
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build:
      context: ./workers/worker
    environment:
      - TAAS_RESULTS_DIR=/workspace/test-results/taas
      - RQ_REDIS_URL=redis://redis:6379/0
    volumes:
      - ./:/workspace
    shm_size: "1gb"
    depends_on:
      - redis
