# sites.yaml
default_site: ratemate

sites:
  ratemate:
    base_url: "https://store.ratemate.top"
    login_path: "/en/login"
    register_path: "/en/register"   # nếu form đăng ký chung trang login, đổi lại "/en/login"
    locales: ["en"]                  # thêm "vi" nếu site đã bật tiếng Việt
    routes:
      - "/en/login"
      - "/en/store"
      - "/en/product"
      - "/en/QR"
  fuchacha:
    base_url: "https://qmtj8pvt-3000.asse.devtunnels.ms"
    login_path: "/login/pwd-login"
    register_path: "/login/pwd-login"
    locales: ["en", "zh"]
    routes:
      - "/login/pwd-login"
      - "/home"
      - "/system-manage/user-manage"

  ratemate_app2:
    base_url: "https://app2.ratemate.top"
    login_path: "/en/login"
    register_path: "/en/login"
    locales: ["en"]
    routes:
      public:
        - "/login"
        - "/en/login"
      protected:
        - "/home"
