# config/sites/ratemate2.yml
base_url: https://store.ratemate.top

auth_paths:
  login: /login
  register: /login  

locales: []          

routes:
  public:
    - /login
  protected:
    - /store
    - /profile
    - /wallet
    - /product
    - /home
