site: ratemate
envs:
  prod:
    base_url: https://store.ratemate.top
    login_path: /en/login
    register_path: /en/login
    routes:
      - /en/login
      - /en/store
      - /en/product
      - /en/QR
  staging:
    base_url: http://192.168.1.7:19068/
    login_path: /en/login
    register_path: /en/login
    routes:
      - /en/login
      - /en/store
      - /en/product
      - /en/QR
locales: [en]
