name: E2E (ratemate)

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  e2e:
    uses: ./.github/workflows/e2e-common.yml
    with:
      site: ratemate
      base_url: https://store.ratemate.top
      login_path: /en/login
      register_path: /en/register
      browsers: "chromium"
      run_login_success: true
    secrets: inherit
