name: E2E (ratemate_app2)

on:
  schedule:
    # 06:00 Asia/Ho_Chi_Minh (UTC+7) => 23:00 UTC (previous day)
    - cron: '0 23 * * *'
    # 18:00 Asia/Ho_Chi_Minh (UTC+7) => 11:00 UTC
    - cron: '0 11 * * *'
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  e2e:
    uses: ./.github/workflows/e2e-common.yml
    with:
      site: ratemate_app2
      base_url: https://app2.ratemate.top
      login_path: /en/login
      register_path: /en/login
      browsers: "chromium"
      run_login_success: false
      pytest_marker: 'smoke'
    secrets: inherit
