name: E2E (fuchacha)

on:
  schedule:
    # 06:00 Asia/Ho_Chi_Minh (UTC+7) => 23:00 UTC (previous day)
    - cron: '0 23 * * *'
    # 18:00 Asia/Ho_Chi_Minh (UTC+7) => 11:00 UTC
    - cron: '0 11 * * *'
  workflow_dispatch: {}

jobs:
  e2e:
    uses: ./.github/workflows/e2e-common.yml
    with:
      site: fuchacha
      base_url: https://qmtj8pvt-3000.asse.devtunnels.ms
      login_path: /login/pwd-login
      register_path: /login/pwd-login
      browsers: "chromium"
      run_login_success: true
    secrets: inherit
