name: E2E

on:
  schedule:
    - cron: "*/30 * * * *"   # 30 phút/lần
  workflow_dispatch: {}

concurrency:
  group: e2e
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      SITE: ratemate
      ENV: prod
      BASE_URL_PROD: https://store.ratemate.top
      LOGIN_PATH: /en/login
      REGISTER_PATH: /en/login
      # đường dẫn JUnit bên trong container (sẽ được copy ra sau)
      JUNIT_XML: /app/report/junit.xml

    steps:
      - uses: actions/checkout@v4

      - name: Build test image
        run: docker build -t ratemate-tests .

      - name: Run tests (Chromium)
        env:
          # Secrets cho case login_success
          E2E_EMAIL: ${{ secrets.E2E_EMAIL }}
          E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}
        run: |
          docker rm -f ratemate_e2e 2>/dev/null || true
          docker run --name ratemate_e2e -t --ipc=host --shm-size=1g --user 0:0 \
            -e SITE -e ENV -e BASE_URL_PROD -e LOGIN_PATH -e REGISTER_PATH \
            -e JUNIT_XML -e E2E_EMAIL -e E2E_PASSWORD \
            ratemate-tests \
            bash -lc "mkdir -p /tmp/pytest_cache /tmp/test-results /app/report && \
              pytest -vv tests/auth tests/smoke/test_routes.py \
                --browser=chromium \
                -p no:pytest_excel \
                -o cache_dir=/tmp/pytest_cache \
                --output=/tmp/test-results \
                --screenshot=only-on-failure --video=off --tracing=retain-on-failure \
                --html=/app/report/auth.html --self-contained-html \
                -o junit_family=xunit2 --junitxml=\$JUNIT_XML || true"

      - name: Copy report out
        run: |
          mkdir -p report
          # Copy đúng file để tránh lồng thư mục
          docker cp ratemate_e2e:/app/report/junit.xml ./report/junit.xml || true
          docker cp ratemate_e2e:/app/report/auth.html ./report/auth.html || true
          docker rm -f ratemate_e2e 2>/dev/null || true
          ls -la report || true
          head -n 20 report/junit.xml || true

      - name: Parse JUnit → summary
        id: sum
        run: |
          python - <<'PY'
          import os, json, pathlib, xml.etree.ElementTree as ET, sys
          p = pathlib.Path("report/junit.xml")
          out = {}
          if p.exists():
            try:
              t = ET.parse(p).getroot()
              ts = t if t.tag.endswith('testsuite') else t.find('.//testsuite')
              def g(a): return int(ts.get(a,"0"))
              out = {
                  "total": g("tests"),
                  "fail": g("failures"),
                  "error": g("errors"),
                  "skip":  g("skipped"),
                  "duration": float(ts.get("time","0")),
                  "fails": [],
              }
              for tc in ts.findall(".//testcase"):
                fe = tc.find("failure") or tc.find("error")
                if fe is not None:
                  name = f"{tc.get('classname','')}.{tc.get('name')}"
                  msg  = (fe.get('message') or '').strip()
                  txt  = (fe.text or '').strip()
                  out["fails"].append({"name": name, "reason": (msg or txt or 'No message')[:400]})
            except Exception as e:
              print("Parse error:", e, file=sys.stderr)
              out = {}
          # ghi ra output cho step sau
          with open(os.environ["GITHUB_OUTPUT"], "a", encoding="utf-8") as fh:
            fh.write("summary_json<<EOF\n")
            fh.write(json.dumps(out, ensure_ascii=False))
            fh.write("\nEOF\n")
          PY

      - name: Send Telegram
        if: always()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_PROXY:     ${{ secrets.TELEGRAM_PROXY }}
          SUMMARY_JSON:       ${{ steps.sum.outputs.summary_json }}
        run: |
          python - <<'PY'
          import json, os, subprocess, xml.etree.ElementTree as ET, pathlib
          # Lấy summary từ output; nếu rỗng thì fallback đọc lại junit.xml
          raw = os.getenv("SUMMARY_JSON") or ""
          d = json.loads(raw) if raw else {}
          if not d:
              p = pathlib.Path("report/junit.xml")
              if p.exists():
                  t = ET.parse(p).getroot()
                  ts = t if t.tag.endswith('testsuite') else t.find('.//testsuite')
                  def g(a): return int(ts.get(a,"0"))
                  d = {"total": g("tests"), "fail": g("failures"), "error": g("errors"),
                       "skip": g("skipped"), "duration": float(ts.get("time","0")), "fails":[]}
                  for tc in ts.findall(".//testcase"):
                      fe = tc.find("failure") or tc.find("error")
                      if fe is not None:
                          name=f"{tc.get('classname','')}.{tc.get('name')}"
                          msg=(fe.get('message') or '').strip()
                          txt=(fe.text or '').strip()
                          d["fails"].append({"name":name,"reason":(msg or txt or 'No message')[:400]})
          total=d.get("total",0); fail=d.get("fail",0); err=d.get("error",0); skip=d.get("skip",0); dur=d.get("duration",0.0)
          status = "✅" if fail==0 and err==0 else "❌"
          lines = [
              f"{status} E2E Result: {total} tests | pass={total-fail-err-skip} fail={fail} error={err} skip={skip}",
              f"Duration: ~{dur:.1f}s",
              f"Run: {os.getenv('GITHUB_SERVER_URL','')}/{os.getenv('GITHUB_REPOSITORY','')}/actions/runs/{os.getenv('GITHUB_RUN_ID','')}",
          ]
          if d.get("fails"):
              lines.append("")
              lines.append("❗ Failed cases:")
              for f in d["fails"][:10]:
                  lines.append(f"• {f['name']}")
                  lines.append(f"  └─ {f['reason']}")
          text = "\n".join(lines)

          token = os.environ["TELEGRAM_BOT_TOKEN"]
          chat  = os.environ["TELEGRAM_CHAT_ID"]
          url   = f"https://api.telegram.org/bot{token}/sendMessage"
          payload = {"chat_id": chat, "text": text, "parse_mode": "HTML", "disable_web_page_preview": True}

          args = ["curl","-sS","-m","60","-X","POST","-H","Content-Type: application/json","-d",json.dumps(payload, ensure_ascii=False)]
          if os.getenv("TELEGRAM_PROXY"):
              args[1:1] = ["-x", os.environ["TELEGRAM_PROXY"]]
          args.append(url)
          res = subprocess.run(args, capture_output=True, text=True)
          print("Telegram:", res.stdout or res.stderr)
          PY

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-report
          path: report/
