name: E2E

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.py'
      - 'tests/**'
      - 'Dockerfile'
      - '.github/workflows/e2e.yml'
      - 'requirements*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env
        run: |
          cat > .env <<'EOF'
          ENV=${{ secrets.ENV }}
          BASE_URL_PROD=${{ secrets.BASE_URL_PROD }}
          LOGIN_PATH=${{ vars.LOGIN_PATH || '/en/login' }}
          REGISTER_PATH=${{ vars.REGISTER_PATH || '/en/login' }}
          LOGIN_EMAIL=${{ secrets.LOGIN_EMAIL }}
          LOGIN_PASSWORD=${{ secrets.LOGIN_PASSWORD }}
          LOCALES=${{ vars.LOCALES || 'en' }}
          EOF

      - name: Build Docker image
        run: docker build -t ratemate-tests .

      - name: Run tests (chromium + webkit)
        env:
          TS: ${{ github.run_id }}-${{ github.run_attempt }}
        run: |
          OUT="$RUNNER_TEMP/e2e-report"
          mkdir -p "$OUT"
          chmod 777 "$OUT"
          docker run --rm --ipc=host --shm-size=1g \
            -v "${{ github.workspace }}:/app" \
            -v "$OUT:/out" \
            -e ARTIFACT_DIR=/out \
            --env-file .env \
            ratemate-tests \
            bash -lc "pytest -vv tests/auth tests/smoke/test_routes.py \
              --browser=chromium --browser=webkit \
              --screenshot=only-on-failure --video=off --tracing=retain-on-failure \
              --excelreport=/out/smoke-${TS}.xlsx"

      - name: Upload Excel report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-report
          path: ${{ runner.temp }}/e2e-report/*.xlsx
          retention-days: 14
          if-no-files-found: warn
